local plugins = {}

vim.list_extend(plugins, require("plugins.editing"))
vim.list_extend(plugins, require("plugins.mason"))
vim.list_extend(plugins, require("plugins.lsp_servers"))
vim.list_extend(plugins, require("plugins.completion"))
vim.list_extend(plugins, require("plugins.treesitter"))
vim.list_extend(plugins, require("plugins.search"))
vim.list_extend(plugins, require("plugins.explorer"))
vim.list_extend(plugins, require("plugins.formatting"))
vim.list_extend(plugins, require("plugins.statusline"))
vim.list_extend(plugins, require("plugins.git"))
vim.list_extend(plugins, require("plugins.terminal"))
vim.list_extend(plugins, require("plugins.theme"))
vim.list_extend(plugins, require("plugins.lint"))
vim.list_extend(plugins, require("plugins.outline"))
vim.list_extend(plugins, require("plugins.mini"))
vim.list_extend(plugins, require("plugins.codewindow"))
vim.list_extend(plugins, require("plugins.refactor"))
vim.list_extend(plugins, require("plugins.diagnostics"))
vim.list_extend(plugins, require("plugins.lsp-ui"))
vim.list_extend(plugins, require("plugins.git-tools"))
vim.list_extend(plugins, require("plugins.lsp-navic"))
vim.list_extend(plugins, require("plugins.which-key"))
vim.list_extend(plugins, require("plugins.venv-selector"))
vim.list_extend(plugins, require("plugins.tags"))
vim.list_extend(plugins, require("plugins.marks"))
vim.list_extend(plugins, require("plugins.markdown"))

return plugins
